name: tape_measure_example
description: Exmaple for tape_measure.
version: 1.0.1+2
homepage: https://github.com/deakjahn/tape_measure

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  tape_measure:
    path: ../

  pedantic: ^1.11.0

flutter:
  uses-material-design: true
