name: tape_measure
description: A Slider replacement widget.
version: 1.0.3
homepage: https://github.com/deakjahn/tape_measure

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
