name: tape_measure
description: A Slider replacement widget.
version: 1.0.2
homepage: https://github.com/deakjahn/tape_measure

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
